name: Build CV PDF

on:
  push:

jobs:
  converttopdf:
    name: Build PDF
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build PDF
        run: |-
          npm install -g md-to-pdf
          echo; echo "Generating PDF"
          cat CV.md | md-to-pdf > "Yiannis Nennes - CV.pdf"
          echo; echo "PDF generated"

      - name: Commit PDF
        run: |
          git config --global user.name "Yiannis Nennes"
          git config --global user.email "yiannis@nenn.es"
          git add "Yiannis Nennes - CV.pdf"
          git commit -m "Build CV PDF"
          git push origin main