name: Build CV

on:
  push:

jobs:
  converttopdf:
    name: Build PDF and DOCX
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build PDF
        run: |-
          npm install -g md-to-pdf
          echo; echo "Generating PDF"
          cat CV.md | md-to-pdf > "Yiannis Nennes - CV.pdf"
          echo; echo "PDF generated"

      - name: Install Pandoc
        run: sudo apt-get install -y pandoc

      - name: Build Docx
        run: |-
          pandoc CV.md -o "Yiannis Nennes - CV.docx"
          echo; echo "DOCX generated"

      - name: Commit
        run: |
          git config --global user.name "Yiannis Nennes"
          git config --global user.email "yiannis@nenn.es"
          git add "Yiannis Nennes - CV.pdf"
          git add "Yiannis Nennes - CV.docx"
          git commit -m "Build CV"
          git push origin main